# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    loaders:
        default:
            filesystem:
                bundle_resources:
                    enabled: true
    controller:
        redirect_response_code: 302
    driver: "imagick"
    resolvers:
        profile_photos:
            web_path:
                # use %kernel.project_dir%/web for Symfony prior to 4.0.0
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "media/cache"
    cache: profile_photos
    enqueue: true
    filter_sets :
        thumb:
            quality: 75
            filters:
                thumbnail: { size: [ 1280, 768 ], mode: outbound }
        profile_pic:
            quality: 75
            filters:
                thumbnail: { size: [ 200, 200 ], mode: outbound }
        profile_pic_min:
            quality: 75
            filters:
                thumbnail: { size: [ 50, 50 ], mode: outbound }
        profile_pic_min_table:
            quality: 75
            filters:
                thumbnail: { size: [ 40, 40 ], mode: outbound }