# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    enqueue: true
    driver: "gd"
    filter_sets :
        thumb:
            quality: 75
            filters:
                thumbnail: { size: [ 1280, 768 ], mode: outbound }
        profile_pic:
            quality: 75
            filters:
                thumbnail: { size: [ 200, 200 ], mode: outbound }
        profile_pic_min:
            quality: 75
            filters:
                thumbnail: { size: [ 50, 50 ], mode: outbound }
        profile_pic_min_table:
            quality: 75
            filters:
                thumbnail: { size: [ 40, 40 ], mode: outbound }