twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'bootstrap_4_layout.html.twig'
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    globals:
        APP_NAME: 'Blog youssef'
        complete: false
        IMAGE_PATH: 'images/posts/'
        __categories: '@App\Controller\CategoryController'
        __notifications: '@App\Controller\NotificationController'
        __security: '@App\Controller\SecurityController'