vich_uploader:
    db_driver: orm

    mappings:
        posts:
            uri_prefix: /uploads/posts
            upload_destination: '%kernel.project_dir%/public/uploads/posts'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        users:
            uri_prefix: /uploads/users
            upload_destination: '%kernel.project_dir%/public/uploads/users'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        images:
            uri_prefix: /uploads/images
            upload_destination: '%kernel.project_dir%/public/uploads/images'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        contact_us:
            uri_prefix: /uploads/contact_us
            upload_destination: '%kernel.project_dir%/public/uploads/contact_us'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        settings:
            uri_prefix: /uploads/settings
            upload_destination: '%kernel.project_dir%/public/uploads/settings'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\UniqidNamer